INSERT INTO USER VALUES (1, 'Ramesh', 'ADF'); 
INSERT INTO USER VALUES (2, 'Khilan', 'FGH'); 
INSERT INTO USER VALUES (3, 'kaushik', 'JSON'); 
INSERT INTO USER VALUES (4, 'Chaitali', 'DISKO'); 
INSERT INTO USER VALUES (5, 'Hardik', 'YHU'); 
INSERT INTO USER VALUES (6, 'Komal', 'HJK'); 
INSERT INTO USER VALUES (7, 'Muffy', 'XYZ'); 